config/routes.rb
Rails.application.routes.draw do
  resources :book_availabilities
  resources :reading_lists
  resources :books
  devise_for :users
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/search', to: 'search#new'
  post '/search', to: 'search#result'
  get '/search/add', to: 'search#new'
  post '/search/add', to: 'search#add'

  post '/search/:bid', to: 'books#remove'
  get '/search/:bid', to: 'search#show'
  get '/search/update/:id', to: 'book_availabilities#update'


end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
    belongs_to :user
    has_many :books
end

app/controllers/reading_lists_controller.rb
class ReadingListsController < ApplicationController
  before_action :set_reading_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /reading_lists or /reading_lists.json
  def index
    @reading_lists = ReadingList.all
  end

  # GET /reading_lists/1 or /reading_lists/1.json
  def show
  end

  # GET /reading_lists/new
  def new
    @reading_list = ReadingList.new
  end

  # GET /reading_lists/1/edit
  def edit
  end

  # POST /reading_lists or /reading_lists.json
  def create
    @reading_list = ReadingList.new(reading_list_params)

    respond_to do |format|
      if @reading_list.save
        format.html { redirect_to @reading_list, notice: "Reading list was successfully created." }
        format.json { render :show, status: :created, location: @reading_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reading_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reading_lists/1 or /reading_lists/1.json
  def update
    respond_to do |format|
      if @reading_list.update(reading_list_params)
        format.html { redirect_to @reading_list, notice: "Reading list was successfully updated." }
        format.json { render :show, status: :ok, location: @reading_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reading_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reading_lists/1 or /reading_lists/1.json
  def destroy
    @reading_list.destroy
    respond_to do |format|
      format.html { redirect_to reading_lists_url, notice: "Reading list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading_list
      @reading_list = ReadingList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reading_list_params
      params.require(:reading_list).permit(:name, :user_id)
    end
end

app/helpers/reading_lists_helper.rb
module ReadingListsHelper
end

app/views/reading_lists/_form.html.erb
<%= form_with(model: reading_list) do |form| %>
  <% if reading_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading_list.errors.count, "error") %> prohibited this reading_list from being saved:</h2>

      <ul>
        <% reading_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%#= form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/reading_lists/edit.html.erb
<h1>Editing Reading List</h1>

<%= render 'form', reading_list: @reading_list %>

<%= link_to 'Show', @reading_list %> |
<%= link_to 'Back', reading_lists_path %>
<%= link_to 'Destroy', @reading_list, class: "btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/reading_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Reading Lists</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reading_lists.each do |reading_list| %>
      <tr>
        <td><%= link_to reading_list.name, reading_list %></td>
        <td><%= reading_list.name %></td>
        <td><%= reading_list.user.email %></td>
        <td><%= reading_list.id %></td>
        <td><%= link_to 'Edit', edit_reading_list_path(reading_list) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reading List', new_reading_list_path %>

app/views/reading_lists/new.html.erb
<h1>New Reading List</h1>

<%= render 'form', reading_list: @reading_list %>

<br/>
<p> Current user is <%= current_user.email %></p>
<br/>
<%= link_to 'Back', reading_lists_path %>

app/views/reading_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reading List Name:</strong>
  <%= @reading_list.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @reading_list.user.email %>
</p>

<% if @reading_list.books.empty? %>

  <p> You don't have any books in this list yet.</p>
  <%= link_to 'Add Book?', search_path, class: "btn btn-primary" %>

<% else %>

  <table>

    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>BID</th>
        <th>Availability</th>
        <th>Location</th>
        <th>Reading List</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        <% @reading_list.books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.bid %></td>
            <td><%= book.availability %></td>
            <td><%= book.location %></td>
            <td><%= book.reading_list_id %></td>
            <td><%= link_to 'Show', book %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
   
  </table>
<% end %>

<%= link_to 'Edit', edit_reading_list_path(@reading_list) %> |
<%= link_to 'Back', reading_lists_path %>