config/routes.rb
Rails.application.routes.draw do
  resources :book_availabilities
  resources :reading_lists
  resources :books
  devise_for :users
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/search', to: 'search#new'
  post '/search', to: 'search#result'
  get '/search/add', to: 'search#new'
  post '/search/add', to: 'search#add'

  post '/search/:bid', to: 'books#remove'
  get '/search/:bid', to: 'search#show'
  get '/search/update/:id', to: 'book_availabilities#update'


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :authenticate_user!, except: [:new, :result, :show]
    before_action :set_client, only: %i[ show result ]

    def new
    end

    def add
        if current_user.books.find_by(bid: params[:bid]).present?
            flash[:notice] = "Book already exists"
            redirect_to books_path
        else
            book = get_book(params[:bid])
            current_user.books<<book
            add_book_availability(book)
            flash[:notice] = "Book successfully added"
            redirect_to books_path
        end
    end

    def result
        @book = Book.new
        @response = get_response(search_params)

        @response.titles.each do |i|
            book = Book.new(book_params(i))
            book.save
        end
    end
    
    def show
        # @result = @response.titles.each.find_by(:bid)
        @details = @client.get_title_details(BID: params[:bid])
        @availability = @client.get_availability_info(BID: params[:bid])
    end
    
    private

        def book_params(title)
            h = {}
            h[:title] = title[:title_name]
            h[:author] = title[:author]
            h[:bid] = title[:bid]
            h[:isbn] = title[:isbn]
            h
        end

        def get_response(params)
            if params.length > 1
                response = @client.search(params)
            else
                redirect_to search_path, notice: "At least one field must be populated"
            end
            response
        end

        def set_client
            @client = ::NLBSG.client(key: ENV["NLB_KEY"], env: :production)
        end


        def search_params
            # permits only these parameters to be passed, and removes it if it is blank
            params[:search].permit(:title, :author, :keywords, :subject).to_h.symbolize_keys.merge({ :media_code => "BK" }).delete_if {|key, value| value.blank? }
        end

        def get_book(bid)
            @book = Book.where(bid: bid).first
        end

end

app/helpers/search_helper.rb
module SearchHelper

    # Return only alphanumeric values

    def to_numeric(input)
        output = input.to_s.gsub(/[^0-9]/, "")
    end



end

app/views/search/add.html.erb
<%= current_user %>
<%= current_user.id %>
<%= current_user.inspect %> <br>

<% current_user.books.each do |book| %>
  <%= book.title %> <br>
<% end %>

app/views/search/new.html.erb
<% provide(:title, "Search") %>

<h1>Search</h1>
<p>
  Type in the desired book title below.
</p>


<%= form_for :search, scope: :search, url: search_path, local:true do |form| %>
  <%= form.label :query, "Title:" %>
  <%= form.text_field :title %><br/>

  <%= form.label :query, "Author:" %>
  <%= form.text_field :author %><br/>

  <%= form.label :query, "Keywords:" %>
  <%= form.text_field :keywords %><br/>

  <%= form.label :query, "Subject" %>
  <%= form.text_field :subject %><br/>
  
  <%= form.submit "Search" %>
<% end %>

app/views/search/result.html.erb
<% provide(:title, "Results") %>

<h1>Results</h1>
  <% if @response.total_records == "0" %>
    <p>We did not find anything matching your search descriptions. Please try again.</p>
  <% else %>
    <p>
      Listing <%= @response.next_record_position %> out of <%= pluralize(@response.total_records.to_i, 'record') %>.
      </br>
    </p>

    <% @response.titles.each do |title| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to title[:title_name], "search/#{title[:bid]}", target: :blank %></h5>
          <%# feels a bit hacky. Any better way? search_path(title[:bid]) doesn't work %>
          <p class="card-text">Author: <%= title[:author] %><br/> BID: <%= title[:bid] %></p>
          
          <%= button_to "Add", search_add_path, params: {bid: title[:bid]}, target: :blank %>

        </div>
      </div><br/>

      
    <% end %>
  <% end %>

app/views/search/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @details.title_name %></h1>
  <p class="lead"><%= @details.author %></p>
  <hr class="my-4">
    ISBN: <%= @details.isbn %><br/>
    <% if @details.publisher%>
        Publisher: <%= @details.publisher %><br/>
    <% end %>
    <% if @details.summary %>
        Summary: <%= @details.summary %><br/>
    <% end %>
</div>


<% @availability.items.each do |item| %>

<div class="card w-50">
  <div class="card-body">
    Library Code: <%= item[:branch_id] %><br/>
    Library Name: <%= item[:branch_name] %><br/>
    Status Code: <%= item[:status_code] %><br/>
    Status Description: <%= item[:status_desc] %><br/>
  </div>
</div><br/>

<% end %>