config/routes.rb
Rails.application.routes.draw do
  resources :book_availabilities
  resources :reading_lists
  resources :books
  devise_for :users
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/search', to: 'search#new'
  post '/search', to: 'search#result'
  get '/search/add', to: 'search#new'
  post '/search/add', to: 'search#add'

  post '/search/:bid', to: 'books#remove'
  get '/search/:bid', to: 'search#show'
  get '/search/update/:id', to: 'book_availabilities#update'


end

app/views/layouts/_dashboard.erb
<h3>Books</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>BID</th>
      <th>Availability</th>
      <th>Location</th>
      <th>Created On</th>
      <th>Updated On</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= book.bid %></td>
        <td>
        <% book.book_availabilities.each do |status| %>
          <% if status.status_code == nil %>
            Nil<br/>
          <% else %>
            <%= status.status_code %><br/>
          <% end %>
        <% end %>
        </td>
        <td>
        <% book.book_availabilities.each do |status| %>
          <%= status.location_code if !status.location_code.nil? %><br/>
        <% end %>
        </td>
        <% if !book.book_availabilities.first.nil? %>
          <td><%= book.book_availabilities.first.created_at.localtime %></td>
          <td><%= book.book_availabilities.first.updated_at.localtime %></td>
        <% else %>
          <td>Nil</td>
          <td>Nil</td>
        <% end %>
        <td>
          <%= link_to 'Edit', edit_book_path(book) %>
          <%= link_to 'Update', "search/update/#{book.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer bg-light">
    <div class="container py-4 pb-5">
        <!-- Footer Links -->
    <hr>
        <small>Bookbook</small>
        <ul class="list-inline" style="float: right">
            <li class="list-inline-item"><%= link_to "About", about_path, class: "text-secondary" %></li>
            <li class="list-inline-item"><%= link_to "Contact", contact_path, class: "text-secondary" %></li>
        </ul>
    </div>


    <!-- Copyright -->
    <div class="footer-copyright bg-secondary text-center py-1 text-light"><small>© 2021 Copyright: Bookbook Sg</small>
    </div>

</footer>
<!-- Footer -->

app/views/layouts/_head.html.erb
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title><%= full_title(yield(:title)) %></title>

  </head>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <%= link_to "Bookbook", root_path, class: "navbar-brand", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto" style="float: right !important;">
      <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Books", books_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Search", search_path, class: "nav-link" %></li>

      <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %></li>
      <% else %>
      <li class="nav-item"><%= link_to "Log In", new_user_session_path, class: "nav-link" %></li>
      <% end %>


    </ul>

  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<%= render 'layouts/head'%>

<body>
  <%= render 'layouts/navbar' %>

  <div class="container pt-5 pb-5">
    <%# If devise/anything else pops up a notice, it will show here %>
    <% if notice %>
    <br />

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <%# <p class="notice"></p> %>
    <% else %>
    <br />
    <% end %>

    <%# Main body from other views will render here. %>

    <%= yield %>
    <br />
  </div>

  <br />
  <br />
  <br />
  <br />
  <br />
  <br />

  <% if Rails.env.development? %>
  <div class="container card">
    <div class="card-body">
      <%= debug(params) %>
    </div>
  </div>
  <% end %>
  <%= render 'layouts/footer' %>


  <%# Bootstrap 4 Jquery%>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
  </script>

</body>

</html>